name: Integration Tests

on:
  pull_request:
    branches:
      - develop
  deployment_status:

jobs:
  integration-tests:
    if: github.event.deployment_status.state == 'success'
    name: Integration tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome97-ff96
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
      - name: Cypress install
        run: yarn add -D cypress

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_SF_HEADER: ${{ secrets.SF_HEADER }}
